#!/bin/bash

echo "🌟 Универсальная программа распознавания чисел v2.2.0"
echo "======================================================="
echo ""
echo "📋 Доступные команды:"
echo ""
echo "🚀 Основные команды:"
echo "  ./run.sh                    - Запуск программы мониторинга"
echo "  ./run.sh --view             - Просмотр сохраненных данных"
echo "  ./run.sh --stats            - Расширенная статистика"
echo "  ./run.sh --series           - Счетчики серий"
echo "  ./run.sh --setup            - Настройка программы"
echo "  ./run.sh --debug            - Режим отладки"
echo "  ./run.sh --config FILE      - Использовать файл конфигурации"
echo "  ./run.sh --export FILE      - Экспорт данных в CSV"
echo "  ./run.sh --clear-stats      - Очистить файл статистики"
echo "  ./run.sh --clear-series     - Сбросить счетчики серий"
echo "  ./run.sh --help             - Показать справку"
echo ""
echo "⚙️  Дополнительные команды:"
echo "  ./install.sh                - Установка зависимостей (macOS)"
echo "  python3 demo.py             - Создать демонстрационные данные"
echo "  ./help.sh                   - Показать эту справку"
echo ""
echo "📁 Важные файлы:"
echo "  config.json                 - Конфигурация программы"
echo "  numbers.json                - Сохраненные данные"
echo "  region.json                 - Сохраненная область экрана"
echo "  README.md                   - Подробная документация"
echo ""
echo "🌐 Поддерживаемые ОС: macOS, Windows, Linux"
echo "🔍 Автоматическое обнаружение Tesseract OCR"
echo ""
echo "📖 Для подробной информации читайте README.md" 